[defaultTotemFeatures]
healthUponUse = 2
clearEffectsUponUse = true

[defaultTotemFeatures.fireResistance]
enabled = true
duration = 1000

[defaultTotemFeatures.regeneration]
enabled = true
duration = 1000
amplifier = 2

[defaultTotemFeatures.absorption]
enabled = true
duration = 200
amplifier = 2
[newTotemFeatures]
canUseTotemFromInventory = false
applyEffectsOnlyWhenNecessary = true
customEffects = [[]]

[newTotemFeatures.waterBreathing]
enabled = true
duration = 900

[newTotemFeatures.destroyBlocks]
whenSuffocating = true
whenFullyFrozen = true

[newTotemFeatures.knockbackMobs]
enabled = true
radius = 4.0
strength = 4.0

[newTotemFeatures.cooldown]
enabled = false
cooldown = 200

[newTotemFeatures.teleportOutOfVoid]
enabled = true
teleportHeightOffset = 64
[charm]
canUseTotemFromCharmSlot = true
displayTotemOnChest = true
[blacklists]
blacklistedDimensions = []
blacklistedStructures = []
